#remote_theme: wowthemesnet/jekyll-theme-memoirs

# Website Info

name: "Maxel's Pages"
title: "Maxel's Pages"
author: "Maxel Black"
description: "Code & write what we want.<br />Here is a simple blog written by a simple person."
logo: '/assets/images/logo.png'
favicon: '/favicon.ico'
url: https://maxelblack.github.io
baseurl:
permalink: /:year/:month/:title/
email: maxelblack@outlook.com
disqus: 'maxels-pages'
google_analytics: "G-0PRRN86LQ0"
google_search_content: "vW3qvqkUTdYACYAKPz1FvhCCQP4lUGCWh8OMdafZKcs"
lisence: '<a target="_blank" href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>'
mailchimp-list:

# Configure

excerpt_separator: "<!--MORE-->"

encoding: UTF-8
#highlighter: none
markdown: kramdown

jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

paginate: 6
paginate_path: /page:num/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

include: ["_pages"]
exclude: [README.md, Gemfile, Gemfile.lock]

# Authers

authors:
  maxelbk:
    name: "Maxel Black"
    display_name: "Maxel Black"
    avatar: 'r/maxel.jpg'
    email: maxelblack@outlook.com
    twitter: https://twitter.com/maxelbk
    description: "A simple student who loves coding."

# Other Things

# Adsense (change to "enabled" to activate, also your client id and ad slot.)
# Create a new ad unit from your Adsense account to get the slot.
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed
